### ISSUE TITLE
move presets from config file to a db

### ISSUE THREAD

**Issue by erickrdch** [commuters/geofence#2]

**Comment by erickrdch** [comment]
i was thinking on something like mongo or redis; the later is already installed on the server but we can also use a more "reliable" service instead of trying to build it ourselves. 

i've used compose.io (previously mongohq) and it is pretty easy to use; as a plus side, they also support redis, postgresql and another handful of services.

**Comment by erickrdch** [comment]
i ended up using compose.io; easier than installing and configuring our own db server. i'll share credentials/create new ones on demand.

mongo uri: mongodb://<user>:<password>@dogen.mongohq.com:10083/geofence

**Comment by parga** [comment]
:+1:
